name = "yukio-bot"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "yukio-db"
database_id = "8b0b931d-b4f7-41c0-885b-6e90c11c8bb7"

[observability]
enabled = true

[triggers]
crons = ["0 3 * * *"]

[vars]
ADMIN_USER_ID = "1605070949"
BUSINESS_OWNER_ID = "1605070949"
DISCORD_APP_ID = "1555992467231215810"
DISCORD_PUBLIC_KEY = "27f6ff67480b1af5ab5d8cd34139ca28834a2b70c85ce09170f146e803822f21"